### ISSUE TITLE
Marte - Components - Forms: Unwanted actions when Enter key pushed

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-marte-changelog#2]
on this demo page: https://codyhouse.co/demo-templates/marte/components-forms.html, when focus in the first input and push the Enter key, the wanted action should be submit, but what you get is:
1. the datepicker dropdown showed;

and, when i remove the entire row of the datepicker from dom (chrome console/F12), when Enter key is pushed: 
2. the number-input auto increased (by step everytime enter pushed);

which are both unwanted actions!
How to change these default unwanted actions?

**Comment by dean-shanghai** [comment]
Original components-forms page: push enter cause datepicker auto pop
![push enter cause datepicker pop](https://user-images.githubusercontent.com/6344066/98466501-ff1c6380-220a-11eb-8e6e-3cb2bd8870f4.gif)

**Comment by dean-shanghai** [comment]
components-forms page (datepicker removed from dom): push enter cause number-input autoincrease
![push enter cause number-input autoincrease](https://user-images.githubusercontent.com/6344066/98466555-3559e300-220b-11eb-87cf-681ee5923081.gif)

**Comment by claudia-romano** [comment]
Hi Dean, this can be fixed adding a `type="button"` to the button elements inside the date picker component and the number input component.

For example, one of the two buttons in the number input component would look like:
```
<button type="button" class="reset number-input__btn number-input__btn--plus js-number-input__btn" aria-label="Increase Number">
  <svg class="icon" viewBox="0 0 16 16" aria-hidden="true"><g><polygon points="13,11 8,5 3,11 "></polygon></g></svg
</button>
```
We'll make sure to update the components and the template asap. Cheers!

**Comment by claudia-romano** [comment]
Hi Dean,
the template has been updated. You can download the new version here:
https://codyhouse.co/template/marte

Cheers!
