### ISSUE TITLE
Widgets init failed if scripts.js is placed in header

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-marte-changelog#3]
Sometimes, it is needed to place scripts.js in the head.
if scripts.js is placed in header, the page will look like this:
![image](https://user-images.githubusercontent.com/6344066/141795156-41bac1ef-d61f-4d19-a8fb-5707b47a5420.png)

**Comment by claudia-romano** [comment]
Hi there, the scripts.js file should be included right before the <body> closing tag to work properly.
If you need to load a specific script in the head, then I suggest you to split them in two and load them separately.
